# Generated by Django 5.1.1 on 2025-03-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='Subject',
            new_name='subject',
        ),
    ]
